App\TSBundle\Entity\Category:
    type: entity
    repositoryClass: App\TSBundle\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
    oneToMany:
        news:
            targetEntity: News
            mappedBy: category
    manyToMany:
        editors:
            targetEntity: Editors
            mappedBy: categories
