App\TSBundle\Entity\Editors:
    type: entity
    repositoryClass: App\TSBundle\Repository\EditorsRepository
    table: editors
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        url:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        token:
            type: string
            length: 255
        is_active:
            type: boolean
            nullable: true
        created_at:
            type: datetime
    manyToMany:
        categories:
            targetEntity: Category
            inversedBy: editors
            joinTable:
                name: category_editors
                joinColumns:
                    editors_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
