App\TSBundle\Entity\News:
    type: entity
    repositoryClass: App\TSBundle\Repository\NewsRepository
    table: news
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 255
            nullable: true
        data:
            type: string
            length: 255
        position:
            type: string
            length: 400
        url:
            type: string
            length: 255
            nullable: true
        description:
            type: text
        token:
            type: string
            length: 255
            unique: true
        isPublic:
            type: boolean
            nullable: true
        isActivated:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: news
            joinColumn:
                name: categoryId
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
        preUpdate: [setUpdatedAtValue]
