<?php

namespace App\TSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EditorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorsRepository extends EntityRepository
{
}
